version: "3.7"
services:
  nginx:
    image: "sleepinglotus/nginx-registry"
    volumes:
      - ./production.conf:/etc/nginx/nginx.conf
      - ~/etc/letsencrypt:/etc/letsencrypt
    container_name: nginx-registry
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - registry
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "6666:5000"
    restart: always
